/**
 * Read-only catalogue snapshot generated from the Luma Foundry shared Google
 * Sheet (Products tab). Do not edit product identity or demo URLs here without
 * updating the source-of-truth sheet first.
 */
export const catalogueMeta = {
  source: "Luma Foundry — Operator Sync / Products",
  goalId: "goal-factory-50",
  syncedAtUtc: "2026-08-27T02:44:28Z",
  activeTemplateCount: 50,
  paymentState: "disconnected",
  syncMode: "manual read-only snapshot",
};

export const products = [
  {
    "id": "prd-axiom-grid",
    "index": "01",
    "name": "Axiom Grid",
    "category": "AI Infrastructure",
    "collection": "systems",
    "previewUrl": "https://lumafoundry-jx4veohg.manus.space/axiom-grid",
    "imageUrl": "https://lumafoundry-jx4veohg.manus.space/manus-storage/axiom-grid-hero_46c3b0f8.png",
    "direction": "A dark infrastructure narrative for teams that need a clearer technical point of view.",
    "tone": "signal-blue",
    "releaseState": "Live preview / checkout offline"
  },
  {
    "id": "prd-selene-agents",
    "index": "02",
    "name": "Selene Agents",
    "category": "Enterprise Agent Orchestration",
    "collection": "systems",
    "previewUrl": "https://lumafoundry-jx4veohg.manus.space/selene-agents",
    "imageUrl": "https://lumafoundry-jx4veohg.manus.space/manus-storage/selene-agents-hero_9dd8b039.png",
    "direction": "A quiet editorial system for work that still needs human judgement at its centre.",
    "tone": "lilac",
    "releaseState": "Live preview / checkout offline"
  },
  {
    "id": "prd-kinetic-mesh",
    "index": "03",
    "name": "Kinetic Mesh",
    "category": "No-Code Automation",
    "collection": "systems",
    "previewUrl": "https://lumafoundry-jx4veohg.manus.space/kinetic-mesh",
    "imageUrl": "https://lumafoundry-jx4veohg.manus.space/manus-storage/kinetic-mesh-hero_682e14df.png",
    "direction": "An industrial product direction for repeatable work that keeps moving with intent.",
    "tone": "amber",
    "releaseState": "Live preview / checkout offline"
  },
  {
    "id": "prd-lattice-labs",
    "index": "04",
    "name": "Lattice Labs",
    "category": "Research Intelligence",
    "collection": "insight",
    "previewUrl": "https://lumafoundry-jx4veohg.manus.space/lattice-labs",
    "imageUrl": "https://lumafoundry-jx4veohg.manus.space/manus-storage/lattice-labs-hero_587c9d31.png",
    "direction": "A focused research direction for organisations that lead with evidence before action.",
    "tone": "paper",
    "releaseState": "Live preview / checkout offline"
  },
  {
    "id": "prd-orbital-ledger",
    "index": "05",
    "name": "Orbital Ledger",
    "category": "CFO Intelligence",
    "collection": "insight",
    "previewUrl": "https://lumafoundry-jx4veohg.manus.space/orbital-ledger",
    "imageUrl": "https://lumafoundry-jx4veohg.manus.space/manus-storage/orbital-ledger-hero_d99df92d.png",
    "direction": "A composed executive narrative for financial planning, priorities, and the next horizon.",
    "tone": "violet",
    "releaseState": "Live preview / checkout offline"
  },
  {
    "id": "prd-stilla-care-systems",
    "index": "06",
    "name": "Stilla Care Systems",
    "category": "Care-Operations AI",
    "collection": "systems",
    "previewUrl": "https://lumafoundry-jx4veohg.manus.space/stilla-care-systems",
    "imageUrl": null,
    "direction": "An original Care-Operations AI direction. Explore the live demo to evaluate its visual language and flow.",
    "tone": "amber",
    "releaseState": "Live preview / checkout offline"
  },
  {
    "id": "prd-morrow-compute",
    "index": "07",
    "name": "Morrow Compute",
    "category": "Edge AI Hardware",
    "collection": "systems",
    "previewUrl": "https://lumafoundry-jx4veohg.manus.space/morrow-compute",
    "imageUrl": null,
    "direction": "An original Edge AI Hardware direction. Explore the live demo to evaluate its visual language and flow.",
    "tone": "signal-blue",
    "releaseState": "Live preview / checkout offline"
  },
  {
    "id": "prd-vanta-proof",
    "index": "08",
    "name": "Vanta Proof",
    "category": "AI Governance and Compliance",
    "collection": "systems",
    "previewUrl": "https://lumafoundry-jx4veohg.manus.space/vanta-proof",
    "imageUrl": null,
    "direction": "An original AI Governance and Compliance direction. Explore the live demo to evaluate its visual language and flow.",
    "tone": "lilac",
    "releaseState": "Live preview / checkout offline"
  },
  {
    "id": "prd-helio-relay",
    "index": "09",
    "name": "Helio Relay",
    "category": "Conversational AI for Service Teams",
    "collection": "systems",
    "previewUrl": "https://lumafoundry-jx4veohg.manus.space/helio-relay",
    "imageUrl": null,
    "direction": "An original Conversational AI for Service Teams direction. Explore the live demo to evaluate its visual language and flow.",
    "tone": "amber",
    "releaseState": "Live preview / checkout offline"
  },
  {
    "id": "prd-folio-forms",
    "index": "10",
    "name": "Folio Forms",
    "category": "Generative Brand Platform",
    "collection": "systems",
    "previewUrl": "https://lumafoundry-jx4veohg.manus.space/folio-forms",
    "imageUrl": null,
    "direction": "An original Generative Brand Platform direction. Explore the live demo to evaluate its visual language and flow.",
    "tone": "signal-blue",
    "releaseState": "Live preview / checkout offline"
  },
  {
    "id": "prd-noor-vale",
    "index": "11",
    "name": "Noor Vale",
    "category": "Editorial Fashion Portfolio",
    "collection": "luxury",
    "previewUrl": "https://lumafoundry-jx4veohg.manus.space/noor-vale",
    "imageUrl": null,
    "direction": "An original Editorial Fashion Portfolio direction. Explore the live demo to evaluate its visual language and flow.",
    "tone": "violet",
    "releaseState": "Live preview / checkout offline"
  },
  {
    "id": "prd-aster-alder",
    "index": "12",
    "name": "Aster & Alder",
    "category": "Fine Jewellery House",
    "collection": "luxury",
    "previewUrl": "https://lumafoundry-jx4veohg.manus.space/aster-alder",
    "imageUrl": null,
    "direction": "An original Fine Jewellery House direction. Explore the live demo to evaluate its visual language and flow.",
    "tone": "amber",
    "releaseState": "Live preview / checkout offline"
  },
  {
    "id": "prd-elan-method",
    "index": "13",
    "name": "Élan Method",
    "category": "Premium Skin Studio",
    "collection": "luxury",
    "previewUrl": "https://lumafoundry-jx4veohg.manus.space/elan-method",
    "imageUrl": null,
    "direction": "An original Premium Skin Studio direction. Explore the live demo to evaluate its visual language and flow.",
    "tone": "paper",
    "releaseState": "Live preview / checkout offline"
  },
  {
    "id": "prd-vela-maison",
    "index": "14",
    "name": "Vela Maison",
    "category": "Couture Bridal Atelier",
    "collection": "luxury",
    "previewUrl": "https://lumafoundry-jx4veohg.manus.space/vela-maison",
    "imageUrl": null,
    "direction": "An original Couture Bridal Atelier direction. Explore the live demo to evaluate its visual language and flow.",
    "tone": "violet",
    "releaseState": "Live preview / checkout offline"
  },
  {
    "id": "prd-sardis-parfums",
    "index": "15",
    "name": "Sardis Parfums",
    "category": "Niche Fragrance Brand",
    "collection": "luxury",
    "previewUrl": "https://lumafoundry-jx4veohg.manus.space/sardis-parfums",
    "imageUrl": null,
    "direction": "An original Niche Fragrance Brand direction. Explore the live demo to evaluate its visual language and flow.",
    "tone": "amber",
    "releaseState": "Live preview / checkout offline"
  },
  {
    "id": "prd-ruth-ibarra-botanics",
    "index": "16",
    "name": "Ruth Ibarra Botanics",
    "category": "Floral Studio",
    "collection": "luxury",
    "previewUrl": "https://lumafoundry-jx4veohg.manus.space/ruth-ibarra-botanics",
    "imageUrl": null,
    "direction": "An original Floral Studio direction. Explore the live demo to evaluate its visual language and flow.",
    "tone": "paper",
    "releaseState": "Live preview / checkout offline"
  },
  {
    "id": "prd-tempo-atelier",
    "index": "17",
    "name": "Tempo Atelier",
    "category": "Independent Watchmaker",
    "collection": "luxury",
    "previewUrl": "https://lumafoundry-jx4veohg.manus.space/tempo-atelier",
    "imageUrl": null,
    "direction": "An original Independent Watchmaker direction. Explore the live demo to evaluate its visual language and flow.",
    "tone": "violet",
    "releaseState": "Live preview / checkout offline"
  },
  {
    "id": "prd-peregrine-editions",
    "index": "18",
    "name": "Peregrine Editions",
    "category": "Art and Object Gallery",
    "collection": "luxury",
    "previewUrl": "https://lumafoundry-jx4veohg.manus.space/peregrine-editions",
    "imageUrl": null,
    "direction": "An original Art and Object Gallery direction. Explore the live demo to evaluate its visual language and flow.",
    "tone": "amber",
    "releaseState": "Live preview / checkout offline"
  },
  {
    "id": "prd-caldera-optical",
    "index": "19",
    "name": "Caldera Optical",
    "category": "Design-Led Eyewear",
    "collection": "luxury",
    "previewUrl": "https://lumafoundry-jx4veohg.manus.space/caldera-optical",
    "imageUrl": null,
    "direction": "An original Design-Led Eyewear direction. Explore the live demo to evaluate its visual language and flow.",
    "tone": "paper",
    "releaseState": "Live preview / checkout offline"
  },
  {
    "id": "prd-mare-house",
    "index": "20",
    "name": "Maré House",
    "category": "Coastal Wellness Retreat",
    "collection": "luxury",
    "previewUrl": "https://lumafoundry-jx4veohg.manus.space/mare-house",
    "imageUrl": null,
    "direction": "An original Coastal Wellness Retreat direction. Explore the live demo to evaluate its visual language and flow.",
    "tone": "violet",
    "releaseState": "Live preview / checkout offline"
  },
  {
    "id": "prd-monolith-works",
    "index": "21",
    "name": "Monolith Works",
    "category": "Contemporary Architecture Practice",
    "collection": "spatial",
    "previewUrl": "https://lumafoundry-jx4veohg.manus.space/monolith-works",
    "imageUrl": null,
    "direction": "An original Contemporary Architecture Practice direction. Explore the live demo to evaluate its visual language and flow.",
    "tone": "lilac",
    "releaseState": "Live preview / checkout offline"
  },
  {
    "id": "prd-nocturne-estates",
    "index": "22",
    "name": "Nocturne Estates",
    "category": "Luxury Property Brokerage",
    "collection": "spatial",
    "previewUrl": "https://lumafoundry-jx4veohg.manus.space/nocturne-estates",
    "imageUrl": null,
    "direction": "An original Luxury Property Brokerage direction. Explore the live demo to evaluate its visual language and flow.",
    "tone": "signal-blue",
    "releaseState": "Live preview / checkout offline"
  },
  {
    "id": "prd-alder-house",
    "index": "23",
    "name": "Alder House",
    "category": "Boutique Hotel",
    "collection": "spatial",
    "previewUrl": "https://lumafoundry-jx4veohg.manus.space/alder-house",
    "imageUrl": null,
    "direction": "An original Boutique Hotel direction. Explore the live demo to evaluate its visual language and flow.",
    "tone": "paper",
    "releaseState": "Live preview / checkout offline"
  },
  {
    "id": "prd-formwell-interiors",
    "index": "24",
    "name": "Formwell Interiors",
    "category": "High-End Residential Interiors",
    "collection": "spatial",
    "previewUrl": "https://lumafoundry-jx4veohg.manus.space/formwell-interiors",
    "imageUrl": null,
    "direction": "An original High-End Residential Interiors direction. Explore the live demo to evaluate its visual language and flow.",
    "tone": "lilac",
    "releaseState": "Live preview / checkout offline"
  },
  {
    "id": "prd-studio-lumen",
    "index": "25",
    "name": "Studio Lumen",
    "category": "Architectural Lighting",
    "collection": "spatial",
    "previewUrl": "https://lumafoundry-jx4veohg.manus.space/studio-lumen",
    "imageUrl": null,
    "direction": "An original Architectural Lighting direction. Explore the live demo to evaluate its visual language and flow.",
    "tone": "signal-blue",
    "releaseState": "Live preview / checkout offline"
  },
  {
    "id": "prd-maison-rook",
    "index": "26",
    "name": "Maison Rook",
    "category": "Private Event Venue",
    "collection": "spatial",
    "previewUrl": "https://lumafoundry-jx4veohg.manus.space/maison-rook",
    "imageUrl": null,
    "direction": "An original Private Event Venue direction. Explore the live demo to evaluate its visual language and flow.",
    "tone": "paper",
    "releaseState": "Live preview / checkout offline"
  },
  {
    "id": "prd-terra-forma",
    "index": "27",
    "name": "Terra Forma",
    "category": "Landscape Architecture Studio",
    "collection": "spatial",
    "previewUrl": "https://lumafoundry-jx4veohg.manus.space/terra-forma",
    "imageUrl": null,
    "direction": "An original Landscape Architecture Studio direction. Explore the live demo to evaluate its visual language and flow.",
    "tone": "lilac",
    "releaseState": "Live preview / checkout offline"
  },
  {
    "id": "prd-veloce-district",
    "index": "28",
    "name": "Veloce District",
    "category": "Urban Mixed-Use Development",
    "collection": "spatial",
    "previewUrl": "https://lumafoundry-jx4veohg.manus.space/veloce-district",
    "imageUrl": null,
    "direction": "An original Urban Mixed-Use Development direction. Explore the live demo to evaluate its visual language and flow.",
    "tone": "signal-blue",
    "releaseState": "Live preview / checkout offline"
  },
  {
    "id": "prd-hinge-hearth",
    "index": "29",
    "name": "Hinge & Hearth",
    "category": "Premium Home Furnishings",
    "collection": "spatial",
    "previewUrl": "https://lumafoundry-jx4veohg.manus.space/hinge-hearth",
    "imageUrl": null,
    "direction": "An original Premium Home Furnishings direction. Explore the live demo to evaluate its visual language and flow.",
    "tone": "paper",
    "releaseState": "Live preview / checkout offline"
  },
  {
    "id": "prd-fieldnote-cabins",
    "index": "30",
    "name": "Fieldnote Cabins",
    "category": "Design Cabins and Escapes",
    "collection": "spatial",
    "previewUrl": "https://lumafoundry-jx4veohg.manus.space/fieldnote-cabins",
    "imageUrl": null,
    "direction": "An original Design Cabins and Escapes direction. Explore the live demo to evaluate its visual language and flow.",
    "tone": "lilac",
    "releaseState": "Live preview / checkout offline"
  },
  {
    "id": "prd-kansa-objects",
    "index": "31",
    "name": "Kansa Objects",
    "category": "Artful Homewares",
    "collection": "objects",
    "previewUrl": "https://lumafoundry-jx4veohg.manus.space/kansa-objects",
    "imageUrl": null,
    "direction": "An original Artful Homewares direction. Explore the live demo to evaluate its visual language and flow.",
    "tone": "amber",
    "releaseState": "Live preview / checkout offline"
  },
  {
    "id": "prd-ora-roasters",
    "index": "32",
    "name": "Ora Roasters",
    "category": "Specialty Coffee Subscription",
    "collection": "objects",
    "previewUrl": "https://lumafoundry-jx4veohg.manus.space/ora-roasters",
    "imageUrl": null,
    "direction": "An original Specialty Coffee Subscription direction. Explore the live demo to evaluate its visual language and flow.",
    "tone": "paper",
    "releaseState": "Live preview / checkout offline"
  },
  {
    "id": "prd-corella-run",
    "index": "33",
    "name": "Corella Run",
    "category": "Premium Running Apparel",
    "collection": "objects",
    "previewUrl": "https://lumafoundry-jx4veohg.manus.space/corella-run",
    "imageUrl": null,
    "direction": "An original Premium Running Apparel direction. Explore the live demo to evaluate its visual language and flow.",
    "tone": "violet",
    "releaseState": "Live preview / checkout offline"
  },
  {
    "id": "prd-solace-audio",
    "index": "34",
    "name": "Solace Audio",
    "category": "High-Fidelity Speakers",
    "collection": "objects",
    "previewUrl": "https://lumafoundry-jx4veohg.manus.space/solace-audio",
    "imageUrl": null,
    "direction": "An original High-Fidelity Speakers direction. Explore the live demo to evaluate its visual language and flow.",
    "tone": "amber",
    "releaseState": "Live preview / checkout offline"
  },
  {
    "id": "prd-basil-bone",
    "index": "35",
    "name": "Basil & Bone",
    "category": "Elevated Pet Goods",
    "collection": "objects",
    "previewUrl": "https://lumafoundry-jx4veohg.manus.space/basil-bone",
    "imageUrl": null,
    "direction": "An original Elevated Pet Goods direction. Explore the live demo to evaluate its visual language and flow.",
    "tone": "paper",
    "releaseState": "Live preview / checkout offline"
  },
  {
    "id": "prd-vesper-pantry",
    "index": "36",
    "name": "Vesper Pantry",
    "category": "Fine Food and Table Goods",
    "collection": "objects",
    "previewUrl": "https://lumafoundry-jx4veohg.manus.space/vesper-pantry",
    "imageUrl": null,
    "direction": "An original Fine Food and Table Goods direction. Explore the live demo to evaluate its visual language and flow.",
    "tone": "violet",
    "releaseState": "Live preview / checkout offline"
  },
  {
    "id": "prd-arq-supply",
    "index": "37",
    "name": "Arq Supply",
    "category": "Design Tools for Architects",
    "collection": "spatial",
    "previewUrl": "https://lumafoundry-jx4veohg.manus.space/arq-supply",
    "imageUrl": null,
    "direction": "An original Design Tools for Architects direction. Explore the live demo to evaluate its visual language and flow.",
    "tone": "signal-blue",
    "releaseState": "Live preview / checkout offline"
  },
  {
    "id": "prd-perrin-carry",
    "index": "38",
    "name": "Perrin Carry",
    "category": "Travel Accessories",
    "collection": "objects",
    "previewUrl": "https://lumafoundry-jx4veohg.manus.space/perrin-carry",
    "imageUrl": null,
    "direction": "An original Travel Accessories direction. Explore the live demo to evaluate its visual language and flow.",
    "tone": "paper",
    "releaseState": "Live preview / checkout offline"
  },
  {
    "id": "prd-wildercare",
    "index": "39",
    "name": "Wildercare",
    "category": "Botanical Personal Care",
    "collection": "luxury",
    "previewUrl": "https://lumafoundry-jx4veohg.manus.space/wildercare",
    "imageUrl": null,
    "direction": "An original Botanical Personal Care direction. Explore the live demo to evaluate its visual language and flow.",
    "tone": "amber",
    "releaseState": "Live preview / checkout offline"
  },
  {
    "id": "prd-havenlark",
    "index": "40",
    "name": "Havenlark",
    "category": "Considered Children’s Design",
    "collection": "objects",
    "previewUrl": "https://lumafoundry-jx4veohg.manus.space/havenlark",
    "imageUrl": null,
    "direction": "An original Considered Children’s Design direction. Explore the live demo to evaluate its visual language and flow.",
    "tone": "amber",
    "releaseState": "Live preview / checkout offline"
  },
  {
    "id": "prd-sable-type",
    "index": "41",
    "name": "Sable & Type",
    "category": "Brand and Digital Agency",
    "collection": "practice",
    "previewUrl": "https://lumafoundry-jx4veohg.manus.space/sable-type",
    "imageUrl": null,
    "direction": "An original Brand and Digital Agency direction. Explore the live demo to evaluate its visual language and flow.",
    "tone": "signal-blue",
    "releaseState": "Live preview / checkout offline"
  },
  {
    "id": "prd-civic-assembly",
    "index": "42",
    "name": "Civic Assembly",
    "category": "Urban Strategy and Place Branding",
    "collection": "spatial",
    "previewUrl": "https://lumafoundry-jx4veohg.manus.space/civic-assembly",
    "imageUrl": null,
    "direction": "An original Urban Strategy and Place Branding direction. Explore the live demo to evaluate its visual language and flow.",
    "tone": "lilac",
    "releaseState": "Live preview / checkout offline"
  },
  {
    "id": "prd-masonry-films",
    "index": "43",
    "name": "Masonry Films",
    "category": "Commercial Production Studio",
    "collection": "practice",
    "previewUrl": "https://lumafoundry-jx4veohg.manus.space/masonry-films",
    "imageUrl": null,
    "direction": "An original Commercial Production Studio direction. Explore the live demo to evaluate its visual language and flow.",
    "tone": "lilac",
    "releaseState": "Live preview / checkout offline"
  },
  {
    "id": "prd-northline-counsel",
    "index": "44",
    "name": "Northline Counsel",
    "category": "Modern Legal Advisory",
    "collection": "practice",
    "previewUrl": "https://lumafoundry-jx4veohg.manus.space/northline-counsel",
    "imageUrl": null,
    "direction": "An original Modern Legal Advisory direction. Explore the live demo to evaluate its visual language and flow.",
    "tone": "signal-blue",
    "releaseState": "Live preview / checkout offline"
  },
  {
    "id": "prd-pattern-school",
    "index": "45",
    "name": "Pattern School",
    "category": "Premium Creative Education",
    "collection": "practice",
    "previewUrl": "https://lumafoundry-jx4veohg.manus.space/pattern-school",
    "imageUrl": null,
    "direction": "An original Premium Creative Education direction. Explore the live demo to evaluate its visual language and flow.",
    "tone": "paper",
    "releaseState": "Live preview / checkout offline"
  },
  {
    "id": "prd-oriel-advisory",
    "index": "46",
    "name": "Oriel Advisory",
    "category": "Strategy and Transformation Consultancy",
    "collection": "practice",
    "previewUrl": "https://lumafoundry-jx4veohg.manus.space/oriel-advisory",
    "imageUrl": null,
    "direction": "An original Strategy and Transformation Consultancy direction. Explore the live demo to evaluate its visual language and flow.",
    "tone": "lilac",
    "releaseState": "Live preview / checkout offline"
  },
  {
    "id": "prd-hinterland-sound",
    "index": "47",
    "name": "Hinterland Sound",
    "category": "Sonic Identity Studio",
    "collection": "practice",
    "previewUrl": "https://lumafoundry-jx4veohg.manus.space/hinterland-sound",
    "imageUrl": null,
    "direction": "An original Sonic Identity Studio direction. Explore the live demo to evaluate its visual language and flow.",
    "tone": "signal-blue",
    "releaseState": "Live preview / checkout offline"
  },
  {
    "id": "prd-quorum-house",
    "index": "48",
    "name": "Quorum House",
    "category": "Culture and Event Experience Studio",
    "collection": "practice",
    "previewUrl": "https://lumafoundry-jx4veohg.manus.space/quorum-house",
    "imageUrl": null,
    "direction": "An original Culture and Event Experience Studio direction. Explore the live demo to evaluate its visual language and flow.",
    "tone": "paper",
    "releaseState": "Live preview / checkout offline"
  },
  {
    "id": "prd-adjacent-talent",
    "index": "49",
    "name": "Adjacent Talent",
    "category": "Executive Creative Search",
    "collection": "practice",
    "previewUrl": "https://lumafoundry-jx4veohg.manus.space/adjacent-talent",
    "imageUrl": null,
    "direction": "An original Executive Creative Search direction. Explore the live demo to evaluate its visual language and flow.",
    "tone": "lilac",
    "releaseState": "Live preview / checkout offline"
  },
  {
    "id": "prd-lumen-co",
    "index": "50",
    "name": "Lumen & Co.",
    "category": "Destination Wedding Planning",
    "collection": "spatial",
    "previewUrl": "https://lumafoundry-jx4veohg.manus.space/lumen-co",
    "imageUrl": null,
    "direction": "An original Destination Wedding Planning direction. Explore the live demo to evaluate its visual language and flow.",
    "tone": "paper",
    "releaseState": "Live preview / checkout offline"
  }
];
