export const OFFICIAL_PRODUCT_ROUTE_TITLES = {
  "/axiom-grid": "Axiom Grid",
  "/selene-agents": "Selene Agents",
  "/kinetic-mesh": "Kinetic Mesh",
  "/lattice-labs": "Lattice Labs",
  "/orbital-ledger": "Orbital Ledger",
  "/stilla-care-systems": "Stilla Care Systems",
  "/morrow-compute": "Morrow Compute",
  "/vanta-proof": "Vanta Proof",
  "/helio-relay": "Helio Relay",
  "/folio-forms": "Folio Forms",
  "/noor-vale": "Noor Vale",
  "/aster-alder": "Aster & Alder",
  "/elan-method": "Elan Method",
  "/vela-maison": "Vela Maison",
  "/sardis-parfums": "Sardis Parfums",
  "/ruth-ibarra-botanics": "Ruth Ibarra Botanics",
  "/tempo-atelier": "Tempo Atelier",
  "/peregrine-editions": "Peregrine Editions",
  "/caldera-optical": "Caldera Optical",
  "/mare-house": "Mare House",
  "/monolith-works": "Monolith Works",
  "/nocturne-estates": "Nocturne Estates",
  "/alder-house": "Alder House",
  "/formwell-interiors": "Formwell Interiors",
  "/studio-lumen": "Studio Lumen",
  "/maison-rook": "Maison Rook",
  "/terra-forma": "Terra Forma",
  "/veloce-district": "Veloce District",
  "/hinge-hearth": "Hinge & Hearth",
  "/fieldnote-cabins": "Fieldnote Cabins",
  "/kansa-objects": "Kansa Objects",
  "/ora-roasters": "Ora Roasters",
  "/corella-run": "Corella Run",
  "/solace-audio": "Solace Audio",
  "/basil-bone": "Basil & Bone",
  "/vesper-pantry": "Vesper Pantry",
  "/arq-supply": "Arq Supply",
  "/perrin-carry": "Perrin Carry",
  "/wildercare": "Wildercare",
  "/havenlark": "Havenlark",
  "/sable-type": "Sable Type",
  "/civic-assembly": "Civic Assembly",
  "/masonry-films": "Masonry Films",
  "/northline-counsel": "Northline Counsel",
  "/pattern-school": "Pattern School",
  "/oriel-advisory": "Oriel Advisory",
  "/hinterland-sound": "Hinterland Sound",
  "/quorum-house": "Quorum House",
  "/adjacent-talent": "Adjacent Talent",
  "/lumen-co": "Lumen & Co",
} as const;

const SPECIAL_ROUTE_TITLES: Record<string, string> = {
  "/": "Luma Foundry — 50 AI Automation Workspace",
  "/ember-signal": "Ember Signal — AI Marketing Intelligence",
  "/luma-intelligence": "Luma Intelligence — Luma Foundry",
  "/workspace": "Luma Foundry Workspace",
  "/404": "Page Not Found — Luma Foundry",
};

export function getDocumentTitle(pathname: string): string {
  const productName = OFFICIAL_PRODUCT_ROUTE_TITLES[pathname as keyof typeof OFFICIAL_PRODUCT_ROUTE_TITLES];
  if (productName) return `${productName} — Luma Foundry`;
  return SPECIAL_ROUTE_TITLES[pathname] ?? "Page Not Found — Luma Foundry";
}
