import { ArrowRight, ArrowUpRight, Gem, Menu, Sparkles, Sun, WandSparkles } from "lucide-react";
import { toast } from "sonner";
import { useBatchReveal } from "@/hooks/useBatchReveal";
import styles from "./luxury-batch-03.css?raw";
import mobileOverrides from "./luxury-batch-03-overrides.css?raw";

const useLuxury = (name: string) => {
  useBatchReveal();
  return () => toast("Private appointment requested", { description: `${name} is presented as a premium template concept.` });
};

export function NoorVale() {
  const inquiry = useLuxury("Noor Vale");
  return <><style>{styles}{mobileOverrides}</style><main className="noor3" id="noor-top"><a className="lux-skip" href="#noor-main">Skip to work</a><header><a href="#noor-top">NOOR <i>VALE</i></a><nav><a href="#work">Work</a><a href="#note">Notes</a><button onClick={inquiry}>Private viewing</button></nav><Menu /></header><section id="noor-main" className="noor3-hero"><p>NEW YORK / LONDON / EVERYWHERE LIGHT FALLS</p><h1>Clothes for<br />a <em>moving</em><br />image.</h1><div><p>Selected fashion worlds, photographed with the texture, movement, and quiet exactness of a memory.</p><a href="#work">Scroll to selected work <ArrowRight /></a></div></section><section id="work" className="noor3-masonry"><figure data-batch-reveal><img src="/manus-storage/noor-fashion-hero_f40d2c42.png" alt="Editorial fashion portrait" /><figcaption>01 / NOCTURNE SILK</figcaption></figure><figure data-batch-reveal><div className="noor3-tone" /><figcaption>02 / PAPER CURRENT</figcaption></figure><figure data-batch-reveal><div className="noor3-word">A<br />face<br />in<br />motion.</div></figure><figure data-batch-reveal><div className="noor3-frame" /><figcaption>03 / STUDY IN OXBLOOD</figcaption></figure></section><section id="note" className="noor3-note" data-batch-reveal><p>THE STUDIO NOTE</p><h2>Image-making<br />with <em>intention.</em></h2><button onClick={inquiry}>Request the private portfolio <ArrowUpRight /></button></section><footer>NOOR VALE / IMAGE DIRECTION <a href="#noor-top">TOP ↑</a></footer></main></>;
}

export function AsterAlder() {
  const book = useLuxury("Aster & Alder");
  return <><style>{styles}</style><main className="aster3" id="aster-top"><a className="lux-skip" href="#aster-main">Skip to collection</a><header><a href="#aster-top">ASTER <span>&</span> ALDER</a><nav><a href="#collection">The collection</a><a href="#craft">Craft</a><button onClick={book}>Reserve a viewing</button></nav><Menu /></header><section id="aster-main" className="aster3-hero"><div><p>OBJECTS TO KEEP CLOSE</p><h1>Formed<br />for a <em>lifetime.</em></h1><p>Fine jewels shaped around light, proportion, and the small significance of being chosen personally.</p><button onClick={book}>Enter the collection <ArrowUpRight /></button></div><figure><img src="/manus-storage/aster-alder-hero_6150ee6b.png" alt="Platinum ring in a midnight jewellery vitrine" /><figcaption><Gem />THE CELESTIAL SOLITAIRE / 2026</figcaption></figure></section><section id="collection" className="aster3-collection" data-batch-reveal><p>THE COLLECTION / 07 OBJECTS</p><div><h2>Quiet brilliance,<br />held <em>in hand.</em></h2><aside><span>01</span><h3>The celestial solitaire</h3><p>Platinum / champagne diamond / made to be viewed slowly.</p></aside></div></section><section id="craft" className="aster3-craft" data-batch-reveal><p>THE MAKING</p><div><span>•</span><span>•</span><span>•</span></div><h2>Nothing rushed.<br />Nothing <em>unconsidered.</em></h2></section><footer>ASTER & ALDER / FINE JEWELS <a href="#aster-top">RETURN ↑</a></footer></main></>;
}

export function ElanMethod() {
  const book = useLuxury("Élan Method");
  return <><style>{styles}</style><main className="elan3" id="elan-top"><a className="lux-skip" href="#elan-main">Skip to treatments</a><header><a href="#elan-top">ÉLAN <i>METHOD</i></a><nav><a href="#treatments">Treatments</a><a href="#approach">Approach</a><button onClick={book}>Book a consultation</button></nav><Menu /></header><section id="elan-main" className="elan3-hero"><figure><img src="/manus-storage/elan-method-hero_3f354c21.png" alt="Soft chrome and pearl skincare still life" /></figure><div><p>ADVANCED SKIN CARE / AT A HUMAN PACE</p><h1>Skin, in<br /><em>its element.</em></h1><p>Élan Method pairs advanced treatment with observation, patience, and a considered plan for your skin.</p><button onClick={book}>Find your method <ArrowRight /></button></div></section><section id="treatments" className="elan3-menu"><div data-batch-reveal><p>THE CARE MENU</p><h2>What your<br />skin asks <em>for now.</em></h2></div><div className="elan3-cards"><article data-batch-reveal><span>01</span><h3>Restore</h3><p>Barrier-led treatments for replenishing the skin’s working rhythm.</p></article><article data-batch-reveal><span>02</span><h3>Refine</h3><p>Targeted work for clarity, texture, and measured renewal.</p></article><article data-batch-reveal><span>03</span><h3>Maintain</h3><p>A soft, precise cadence to keep results feeling like you.</p></article></div></section><section id="approach" className="elan3-close" data-batch-reveal><Sun /><h2>Care informed<br />by <em>attention.</em></h2><button onClick={book}>Book your first consultation <ArrowUpRight /></button></section><footer>ÉLAN METHOD / SKIN STUDIO <a href="#elan-top">TOP ↑</a></footer></main></>;
}

export function VelaMaison() {
  const visit = useLuxury("Vela Maison");
  return <><style>{styles}</style><main className="vela3" id="vela-top"><a className="lux-skip" href="#vela-main">Skip to collection</a><header><a href="#vela-top">VELA <i>MAISON</i></a><nav><a href="#silhouettes">Silhouettes</a><a href="#atelier">Atelier</a><button onClick={visit}>Visit the atelier</button></nav><Menu /></header><section id="vela-main" className="vela3-hero"><figure><img src="/manus-storage/vela-maison-hero_742c864d.png" alt="Ivory silk couture gown in a sunlit atelier" /></figure><div><p>THE COUTURE BRIDAL ATELIER</p><h1>Made for the<br /><em>moment</em><br />only you<br />will know.</h1><button onClick={visit}>Discover the collection <ArrowRight /></button></div></section><section id="silhouettes" className="vela3-silhouettes"><article data-batch-reveal><span>01</span><h2>THE<br /><em>LINE</em></h2><p>A silhouette starts with the way you move through a room.</p></article><article data-batch-reveal><span>02</span><h2>THE<br /><em>LIGHT</em></h2><p>Fabric that changes character as the day asks it to.</p></article><article data-batch-reveal><span>03</span><h2>THE<br /><em>MEMORY</em></h2><p>Details that are private, intentional, and entirely your own.</p></article></section><section id="atelier" className="vela3-close" data-batch-reveal><p>THE ATELIER IS OPEN BY APPOINTMENT</p><h2>Begin with<br />a <em>conversation.</em></h2><button onClick={visit}>Plan an atelier visit <ArrowUpRight /></button></section><footer>VELA MAISON / COUTURE BRIDAL <a href="#vela-top">BACK TO LIGHT ↑</a></footer></main></>;
}

export function SardisParfums() {
  const sample = useLuxury("Sardis Parfums");
  return <><style>{styles}</style><main className="sardis3" id="sardis-top"><a className="lux-skip" href="#sardis-main">Skip to scents</a><header><a href="#sardis-top">SARDIS <i>PARFUMS</i></a><nav><a href="#scents">Scents</a><a href="#ingredients">Ingredients</a><button onClick={sample}>Order discovery set</button></nav><Menu /></header><section id="sardis-main" className="sardis3-hero"><div><p>PERFUME FOR THE SCENE, NOT THE SHELF</p><h1>Leave a<br /><em>beautiful trace.</em></h1><p>Sardis makes aromatic scenes from rare materials, slow light, and the memory of somewhere you have never been.</p><button onClick={sample}>Meet the scent worlds <ArrowRight /></button></div><figure><img src="/manus-storage/sardis-parfums-hero_fb56c403.png" alt="Amber perfume bottle staged with saffron on volcanic stone" /><figcaption>SAFFRON / SMOKE / 01:17 AM</figcaption></figure></section><section id="scents" className="sardis3-worlds"><article data-batch-reveal><span>01</span><h2>EMBER<br /><em>STILL</em></h2><p>Incense, leather, and the mineral quiet after rain.</p></article><article data-batch-reveal><span>02</span><h2>GOLDEN<br /><em>HOUR</em></h2><p>Saffron, osmanthus, and sun held on warm skin.</p></article><article data-batch-reveal><span>03</span><h2>BLUE<br /><em>HOLLOW</em></h2><p>Salt, iris, and a far-off low tide.</p></article></section><section id="ingredients" className="sardis3-close" data-batch-reveal><WandSparkles /><p>THE DISCOVERY SET / FOUR SCENTS</p><h2>Start with a<br /><em>scene.</em></h2><button onClick={sample}>Order the discovery set <ArrowUpRight /></button></section><footer>SARDIS PARFUMS / COMPOSED IN SCENES <a href="#sardis-top">RETURN TO NIGHT ↑</a></footer></main></>;
}
