import { ArrowRight, ArrowUpRight, CalendarDays, MapPinned, Mountain, TreePine } from "lucide-react";
import { toast } from "sonner";
import { useBatchReveal } from "@/hooks/useBatchReveal";
import styles from "./spatial-batch-06.css?raw";
import qcStyles from "./fieldnote-qc.css?raw";
const useS=(brand:string)=>{useBatchReveal();return()=>toast("Enquiry requested",{description:`${brand} is shown as a premium template concept.`})};
export function MaisonRook(){const ask=useS("Maison Rook");return <><style>{styles}</style><main className="rook6" id="top"><header><b>MAISON ROOK</b><nav>SPACES　 STORIES　 <button onClick={ask}>REQUEST A DATE</button></nav></header><section className="r-hero"><p>THE PRIVATE HOUSE FOR CELEBRATIONS</p><h1>A room<br/>for the <i>rare</i><br/>occasion.</h1><div><span/><span/><span/><button onClick={ask}>See the house <ArrowRight/></button></div></section><section className="r-calendar" data-batch-reveal><CalendarDays/><h2>MAKE A<br/><i>DATE</i><br/>WITH THE<br/>MOMENT.</h2><button onClick={ask}>Request the diary <ArrowUpRight/></button></section><footer>MAISON ROOK <a href="#top">TOP ↑</a></footer></main></>}
export function TerraForma(){const ask=useS("Terra Forma");return <><style>{styles}</style><main className="terra6" id="top"><header><b>TERRA<br/>FORMA</b><nav>LANDSCAPES　 FIELD NOTES　 <button onClick={ask}>DISCUSS A SITE</button></nav></header><section><div><p>LANDSCAPE ARCHITECTURE / LIVING SYSTEMS</p><h1>Let the<br/><i>land</i><br/>lead.</h1><button onClick={ask}>Follow the contours <ArrowRight/></button></div><figure><i/><i/><i/><i/><span>01 / WETLAND COMMONS</span></figure></section><aside data-batch-reveal><TreePine/><p>Ecology makes the brief more interesting.</p></aside><footer>TERRA FORMA / LIVING LANDSCAPES <a href="#top">SOURCE ↑</a></footer></main></>}
export function VeloceDistrict(){const ask=useS("Veloce District");return <><style>{styles}</style><main className="veloce6" id="top"><header><b>VELOCE<br/>DISTRICT</b><nav>THE DISTRICT　 LIVE　 <button onClick={ask}>REGISTER INTEREST</button></nav></header><section><div className="v-type"><p>THE NEW MIXED-USE QUARTER</p><h1>THE CITY<br/>KEEPS<br/><i>MOVING.</i></h1></div><div className="v-grid"><span>01</span><span>02</span><span>03</span><span>04</span><button onClick={ask}>Take the first turn <ArrowRight/></button></div></section><section className="v-way" data-batch-reveal><MapPinned/><h2>LIVE / WORK /<br/><i>STAY / PLAY</i></h2></section><footer>VELOCE DISTRICT <a href="#top">START ↑</a></footer></main></>}
export function HingeHearth(){const ask=useS("Hinge & Hearth");return <><style>{styles}</style><main className="hinge6" id="top"><header><b>HINGE <i>&</i> HEARTH</b><nav>NEW OBJECTS　 TRADE　 <button onClick={ask}>SHOP THE HOME</button></nav></header><section><div><p>FURNITURE WITH A POINT OF VIEW</p><h1>Make<br/>room for<br/><i>character.</i></h1><button onClick={ask}>Browse the home <ArrowRight/></button></div><figure><span>CHAIR 001<br/>BRICK / COBALT</span><i/><i/></figure></section><section className="h-rail" data-batch-reveal><article>THE<br/>RED<br/>CHAIR</article><article>THE<br/>BLUE<br/>LAMP</article><article>THE<br/>GOOD<br/>TABLE</article></section><footer>HINGE & HEARTH / RADICAL CATALOGUE <a href="#top">TOP ↑</a></footer></main></>}
export function FieldnoteCabins(){const ask=useS("Fieldnote Cabins");return <><style>{styles+qcStyles}</style><main className="field6" id="top"><header><b>FIELDNOTE<br/>CABINS</b><nav>CABINS　 FIELD GUIDE　 <button onClick={ask}>PLAN A STAY</button></nav></header><section><div><p>SMALL PLACES / WIDE COUNTRY</p><h1>Go where<br/>the <i>quiet</i><br/>is.</h1><p>A small collection of thoughtful cabins at the edge of the useful world.</p><button onClick={ask}>Find a cabin <ArrowRight/></button></div><figure><Mountain/><span>RIVER STONE / PINE / FOG</span></figure></section><section className="f-trail" data-batch-reveal><p>THE FIELD GUIDE</p><h2>Pack light.<br/>Look <i>long.</i></h2><button onClick={ask}>Plan the stay <ArrowUpRight/></button></section><footer>FIELDNOTE CABINS <a href="#top">TRAILHEAD ↑</a></footer></main></>}
