import { ArrowRight, ArrowUpRight, Lightbulb, Map } from "lucide-react";
import { toast } from "sonner";
import { useBatchReveal } from "@/hooks/useBatchReveal";
import styles from "./architecture-batch-05.css?raw";
const useA=(name:string)=>{useBatchReveal();return()=>toast("Enquiry requested",{description:`${name} is a premium template concept.`})};
const Skip=({id}:{id:string})=><a className="skip-link" href={`#${id}`}>Skip to content</a>;
export function MonolithWorks(){const ask=useA("Monolith Works"),id="monolith-main";return <><style>{styles}</style><Skip id={id}/><main className="mono5" id={id} tabIndex={-1}><header><b>MONOLITH<br/>WORKS</b><nav>PROJECTS　 JOURNAL　 <button onClick={ask}>STUDIO ENQUIRY</button></nav></header><section><div><p>ARCHITECTURE AS PUBLIC WORK</p><h1>Make<br/>the <i>ground</i><br/>matter.</h1><button onClick={ask}>View project archive <ArrowRight/></button></div><figure><span>01</span><i/><i/><i/><em>INSTITUTIONS / CULTURE / 2026</em></figure></section><aside data-batch-reveal>Selected work moves from the shared ground outward.</aside><footer>MONOLITH WORKS <a href={`#${id}`}>TOP ↑</a></footer></main></>}
export function NocturneEstates(){const ask=useA("Nocturne Estates"),id="nocturne-main";return <><style>{styles}</style><Skip id={id}/><main className="nocturne5" id={id} tabIndex={-1}><header><b>NOCTURNE<br/><i>ESTATES</i></b><nav>RESIDENCES　 NEIGHBOURHOODS　 <button onClick={ask}>ARRANGE A VIEWING</button></nav></header><section><div><p>QUIETLY EXCEPTIONAL RESIDENCES</p><h1>Places<br/>to come<br/><i>home</i> to.</h1><button onClick={ask}>Explore signature homes <ArrowRight/></button></div><figure><span>01 / HILLSIDE RESIDENCE</span><div/></figure></section><section className="n-map" data-batch-reveal><Map/><h2>Where<br/>your next<br/><i>chapter</i> sits.</h2></section><footer>NOCTURNE ESTATES <a href={`#${id}`}>RETURN ↑</a></footer></main></>}
export function AlderHouse(){const ask=useA("Alder House"),id="alder-main";return <><style>{styles}</style><Skip id={id}/><main className="alder5" id={id} tabIndex={-1}><header><b>ALDER <i>HOUSE</i></b><nav>ROOMS　 THE TABLE　 <button onClick={ask}>CHECK AVAILABILITY</button></nav></header><section><div><p>ROOMS HELD BY THE HILLS</p><h1>A good stay<br/>has its own<br/><i>rhythm.</i></h1><button onClick={ask}>Find a room <ArrowRight/></button></div><figure><span>ARRIVE SLOWLY / STAY AWHILE</span></figure></section><section className="a-ledger" data-batch-reveal><p>THE GUEST LEDGER</p><h2>Breakfast at eight.<br/><i>Nothing after.</i></h2></section><footer>ALDER HOUSE / HOTEL & TABLE <a href={`#${id}`}>START ↑</a></footer></main></>}
export function FormwellInteriors(){const ask=useA("Formwell Interiors"),id="formwell-main";return <><style>{styles}</style><Skip id={id}/><main className="form5" id={id} tabIndex={-1}><header><b>FORMWELL<br/>INTERIORS</b><nav>HOMES　 MATERIALS　 <button onClick={ask}>START A PROJECT</button></nav></header><section><div><p>SPACES THAT HOLD THEIR OWN</p><h1>Material<br/>with <i>memory.</i></h1><p>Interiors held together by touch, proportion, and lived-in light.</p><button onClick={ask}>See selected homes <ArrowRight/></button></div><figure><i/><i/><i/><span>OAK / PLUM / CHALK</span></figure></section><section className="f-board" data-batch-reveal><span>01</span><h2>Not decoration.<br/><i>Atmosphere.</i></h2></section><footer>FORMWELL INTERIORS <a href={`#${id}`}>TOP ↑</a></footer></main></>}
export function StudioLumen(){const ask=useA("Studio Lumen"),id="lumen-main";return <><style>{styles}</style><Skip id={id}/><main className="lumen5" id={id} tabIndex={-1}><header><b>STUDIO<br/>LUMEN</b><nav>SYSTEMS　 STUDIES　 <button onClick={ask}>SPEC A SYSTEM</button></nav></header><section><div><p>ARCHITECTURAL LIGHTING LABORATORY</p><h1>Give<br/>light <i>form.</i></h1><button onClick={ask}>Explore lighting systems <ArrowRight/></button></div><figure><span/><i/><em>01 / LUMINANCE STUDY</em></figure></section><section className="l-spec" data-batch-reveal><Lightbulb/><h2>From dark,<br/><i>definition.</i></h2><button onClick={ask}>Request a specification <ArrowUpRight/></button></section><footer>STUDIO LUMEN <a href={`#${id}`}>RETURN ↑</a></footer></main></>}
